package com.dkbaffour.backend.model;

import com.fasterxml.jackson.annotation.JsonBackReference;
import jakarta.persistence.*;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

import java.time.LocalDate;
import java.time.LocalDateTime;

@Entity
@Data // Lombok annotation to generate getters and setters
@Table(
    uniqueConstraints = {
        @UniqueConstraint(columnNames = {"creationDate", "employeeName", "breakType", "workstation_id"})
    }
)
public class BreakLog {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false)
    private String employeeName;

    @Column(nullable = false)
    private String breakType;

    private LocalDateTime punchOut;

    private LocalDateTime punchIn;

    private String timeSpent;

    @ManyToOne
    @JoinColumn(name = "workstation_id")
    @EqualsAndHashCode.Exclude
    @ToString.Exclude
    @JsonBackReference
    private Workstation workstation;

    @Column(updatable = false)
    private LocalDate creationDate;

    @PrePersist
    protected void onCreate() {
        creationDate = LocalDate.now();
    }

    // Getters and setters are automatically generated by Lombok
}
