package com.dkbaffour.backend.model;

import com.fasterxml.jackson.annotation.JsonBackReference;
import jakarta.persistence.*;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

@Entity
@Data // Lombok annotation to generate getters and setters
public class BreakLog {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String employeeName;

    private String breakType;

    private Number punchOut;

    private Number punchIn;

    private String timeSpent;

    @ManyToOne
    @JoinColumn(name = "workstation_id")
    @EqualsAndHashCode.Exclude
    @ToString.Exclude
    @JsonBackReference
    private Workstation workstation;

    // Getters and setters are automatically generated by Lombok
}
