package com.dkbaffour.backend.model;

import jakarta.persistence.*;
import lombok.Data;

import java.util.ArrayList;
import java.util.List;

@Entity
@Data // Lombok annotation to generate getters and setters
public class Workstation {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String name;
    @ElementCollection
    private List<String> members = new ArrayList<>();

    // Getters and setters are automatically generated by lombok
}
